import time from "../assets/timewall-logo.png";
import lootably from "../assets/lootably-logo.png";
import ayetLogo from "../assets/ayetLogo.webp";
import revu from "../assets/revu-logo-white.svg";
import AdGemGlow from "../assets/AdGemGlow.webp";
import offertoroLogo from "../assets/offertoroLogo.webp";
import AdGatemediaGlow from "../assets/AdGatemediaGlow.png";
import monlixLogo from "../assets/monlix-logo.svg";
import { RiMoneyPoundBoxFill } from "react-icons/ri";
import { GiWantedReward } from "react-icons/gi";
import { MdLeaderboard } from "react-icons/md";
import { BsCashStack } from "react-icons/bs";
import { TbAffiliateFilled } from "react-icons/tb";
import { MdStorefront } from "react-icons/md";
import { BiSolidMessageAltDetail } from "react-icons/bi";
import { IoHomeSharp } from "react-icons/io5";
import { FaMusic } from "react-icons/fa6";

import {
  gamePhoto0,
  gamePhoto1,
  gamePhoto2,
  gamePhoto3,
  gamePhoto4,
  gamePhoto5,
  gamePhoto6,
  gamePhoto7,
  gamePhoto8,
  gamePhoto9,
  gamePhoto10,
  gamePhoto11,
  gamePhoto12,
  gamePhoto13,
  gamePhoto14,
  gamePhoto15,
  gamePhoto16,
  gamePhoto17,
  gamePhoto18,
  gamePhoto19,
  gamePhoto20,
  gamePhoto21,
  gamePhoto22,
  gamePhoto23,
  gamePhoto24,
  gamePhoto25,
  gamePhoto26,
  gamePhoto27,
  gamePhoto28,
  gamePhoto29,
  gamePhoto30,
  gamePhoto31,
  gamePhoto32,
  gamePhoto33,
  gamePhoto34,
  gamePhoto35,
  gamePhoto36,
  gamePhoto37,
  gamePhoto38,
  gamePhoto39,
  gamePhoto40,
  gamePhoto41,
  gamePhoto42,
  gamePhoto43,
  gamePhoto44,
  gamePhoto45,
  gamePhoto46,
  gamePhoto47,
  gamePhoto48,
  gamePhoto49,
  gamePhoto50,
  gamePhoto51,
  gamePhoto52,
  gamePhoto53,
  gamePhoto54,
  gamePhoto55,
  gamePhoto56,
  gamePhoto57,
  gamePhoto58,
  gamePhoto59,
  gamePhoto60,
  gamePhoto61,
  gamePhoto62,
  gamePhoto63,
  gamePhoto64,
  gamePhoto65,
  gamePhoto66,
  gamePhoto67,
  gamePhoto68,
  gamePhoto69,
  gamePhoto70,
  gamePhoto71,
  gamePhoto72,
  gamePhoto73,
  gamePhoto74,
  gamePhoto75,
  gamePhoto76,
  gamePhoto77,
  gamePhoto78,
  gamePhoto79,
  gamePhoto80,
  gamePhoto81,
  gamePhoto82,
  gamePhoto83,
  gamePhoto84,
  gamePhoto85,
  gamePhoto86,
  gamePhoto87,
  gamePhoto88,
  gamePhoto89,
  gamePhoto90,
  gamePhoto91,
  gamePhoto92,
  gamePhoto93,
  gamePhoto94,
  gamePhoto95,
  gamePhoto96,
  gamePhoto97,
  gamePhoto98,
  gamePhoto99,
  gamePhoto100,
  gamePhoto101,
  gamePhoto102,
  gamePhoto103,
  gamePhoto104,
  gamePhoto105,
  gamePhoto106,
  gamePhoto107,
  gamePhoto108,
  gamePhoto109,
  gamePhoto110,
  gamePhoto111,
  gamePhoto112,
  gamePhoto113,
  gamePhoto114,
  gamePhoto115,
  gamePhoto116,
  gamePhoto117,
  gamePhoto118,
  gamePhoto119,
  gamePhoto120,
} from "../assets";

export const gamePhotosArray = [
  gamePhoto0,
  gamePhoto1,
  gamePhoto2,
  gamePhoto3,
  gamePhoto4,
  gamePhoto5,
  gamePhoto6,
  gamePhoto7,
  gamePhoto8,
  gamePhoto9,
  gamePhoto10,
  gamePhoto11,
  gamePhoto12,
  gamePhoto13,
  gamePhoto14,
  gamePhoto15,
  gamePhoto16,
  gamePhoto17,
  gamePhoto18,
  gamePhoto19,
  gamePhoto20,
  gamePhoto21,
  gamePhoto22,
  gamePhoto23,
  gamePhoto24,
  gamePhoto25,
  gamePhoto26,
  gamePhoto27,
  gamePhoto28,
  gamePhoto29,
  gamePhoto30,
  gamePhoto31,
  gamePhoto32,
  gamePhoto33,
  gamePhoto34,
  gamePhoto35,
  gamePhoto36,
  gamePhoto37,
  gamePhoto38,
  gamePhoto39,
  gamePhoto40,
  gamePhoto41,
  gamePhoto42,
  gamePhoto43,
  gamePhoto44,
  gamePhoto45,
  gamePhoto46,
  gamePhoto47,
  gamePhoto48,
  gamePhoto49,
  gamePhoto50,
  gamePhoto51,
  gamePhoto52,
  gamePhoto53,
  gamePhoto54,
  gamePhoto55,
  gamePhoto56,
  gamePhoto57,
  gamePhoto58,
  gamePhoto59,
  gamePhoto60,
  gamePhoto61,
  gamePhoto62,
  gamePhoto63,
  gamePhoto64,
  gamePhoto65,
  gamePhoto66,
  gamePhoto67,
  gamePhoto68,
  gamePhoto69,
  gamePhoto70,
  gamePhoto71,
  gamePhoto72,
  gamePhoto73,
  gamePhoto74,
  gamePhoto75,
  gamePhoto76,
  gamePhoto77,
  gamePhoto78,
  gamePhoto79,
  gamePhoto80,
  gamePhoto81,
  gamePhoto82,
  gamePhoto83,
  gamePhoto84,
  gamePhoto85,
  gamePhoto86,
  gamePhoto87,
  gamePhoto88,
  gamePhoto89,
  gamePhoto90,
  gamePhoto91,
  gamePhoto92,
  gamePhoto93,
  gamePhoto94,
  gamePhoto95,
  gamePhoto96,
  gamePhoto97,
  gamePhoto98,
  gamePhoto99,
  gamePhoto100,
  gamePhoto101,
  gamePhoto102,
  gamePhoto103,
  gamePhoto104,
  gamePhoto105,
  gamePhoto106,
  gamePhoto107,
  gamePhoto108,
  gamePhoto109,
  gamePhoto110,
  gamePhoto111,
  gamePhoto112,
  gamePhoto113,
  gamePhoto114,
  gamePhoto115,
  gamePhoto116,
  gamePhoto117,
  gamePhoto118,
  gamePhoto119,
  gamePhoto120,
];

import {
  paypalShopLogo,
  bitcoinShopLogo,
  amazonShopLogo,
  appleShopLogo,
  googleplayShopLogo,
  fortniteShopLogo,
  blizzardShopLogo,
  netflixShopLogo,
  lolShopLogo,
  nintendoShopLogo,
  playstationShopLogo,
  faucet,
  xboxliveShopLogo,
  valorantShopBg,
  zalandoShopLogo,
  visaShopLogo,
  doorDashShopLogo,
  steamShopLogo,
  robloxShopLogo,
  ubereatsShopLogo,
  justEatShopLogo,
  ethereumShopLogo,
  dogecoinShopLogo,
  csgoShopLogo,
  achShopLogo,
} from "../assets";

export const sidebareItems = [
  {
    title: "Home",
    path: "/",
    icon: <IoHomeSharp />,
  },
  {
    title: "Earn",
    path: "earn",
    icon: <RiMoneyPoundBoxFill />,
  },
  {
    title: "Rewards",
    path: "rewards",
    icon: <GiWantedReward />,
  },
  {
    title: "Private Chat",
    path: "privatechat",
    icon: <BiSolidMessageAltDetail />,
  },
  {
    title: "Market Place",
    path: "marketplace",
    icon: <MdStorefront />,
  },
  {
    title: "Musics",
    path: "musics",
    icon: <FaMusic />,
  },
  {
    title: "Leaderboard",
    path: "leaderboard",
    icon: <MdLeaderboard />,
  },
  {
    title: "Affiliates",
    path: "affiliates",
    icon: <TbAffiliateFilled />,
  },
  {
    title: "Cashout",
    path: "cashout",
    icon: <BsCashStack />,
  },
];

export const withdrawCash = [
  { bgColor: "bg-[#2187c7]", image: paypalShopLogo },
  { bgColor: "bg-[#f89723]", image: bitcoinShopLogo },
  { bgColor: "bg-[#11171e]", image: amazonShopLogo },
  { bgColor: "bg-[#b753c7]", image: appleShopLogo },
  { bgColor: "bg-[#ffffff]", image: googleplayShopLogo },
  { bgColor: "bg-[#2187c7]", image: fortniteShopLogo },
  { bgColor: "bg-[#0b1015]", image: blizzardShopLogo },
  { bgColor: "bg-[#ffffff]", image: netflixShopLogo },
];

export const withdrawGiftCards = [
  { bgColor: "bg-[#416d2d]", image: lolShopLogo },
  { bgColor: "bg-[#ff000a]", image: nintendoShopLogo },
  { bgColor: "bg-[#4042bb]", image: playstationShopLogo },
  { bgColor: "bg-[#0b5555]", image: faucet },
  { bgColor: "bg-[#2dab3d]", image: xboxliveShopLogo },
  { bgColor: "bg-[#ff4655]", image: valorantShopBg },
  { bgColor: "bg-[#11fd30]", image: zalandoShopLogo },
  { bgColor: "bg-[#ffffff]", image: visaShopLogo },
  { bgColor: "bg-[#691919]", image: doorDashShopLogo },
  { bgColor: "bg-[#bab4df]", image: steamShopLogo },
  { bgColor: "bg-[#640f59]", image: robloxShopLogo },
  { bgColor: "bg-[#1601015d]", image: ubereatsShopLogo },
  { bgColor: "bg-[#2ea57d]", image: justEatShopLogo },
];

export const withdrawSkins = [
  { bgColor: "bg-[#35a596]", image: ethereumShopLogo },
  { bgColor: "bg-[#5d9926]", image: dogecoinShopLogo },
  { bgColor: "bg-[#4042bb]", image: csgoShopLogo },
  { bgColor: "bg-[#662b04]", image: achShopLogo },
];

export const arrayoffers = [
  { image: time, title: "BitLaps" },
  { image: lootably, title: "lootaby" },
  { image: ayetLogo, title: "AyetLogo" },
  { image: revu, title: "Revenue Univers" },
  { image: AdGemGlow, title: "AdGate" },
  { image: offertoroLogo, title: "offertoro" },
  { image: AdGatemediaGlow, title: "AdGatemed" },
  { image: monlixLogo, title: "Monlix" },
];
